-- Drop tables in correct order
DROP TABLE Topic_Rating CASCADE CONSTRAINTS;
DROP TABLE Moderation_Log CASCADE CONSTRAINTS;
DROP TABLE Notification CASCADE CONSTRAINTS;
DROP TABLE Message CASCADE CONSTRAINTS;
DROP TABLE Attachment CASCADE CONSTRAINTS;
DROP TABLE Comment_ CASCADE CONSTRAINTS;
DROP TABLE Topic_Tag CASCADE CONSTRAINTS;
DROP TABLE Tag CASCADE CONSTRAINTS;
DROP TABLE Topic CASCADE CONSTRAINTS;
DROP TABLE Category CASCADE CONSTRAINTS;
DROP TABLE Roles_Permissions CASCADE CONSTRAINTS;
DROP TABLE "User" CASCADE CONSTRAINTS;
DROP TABLE Permissions CASCADE CONSTRAINTS;
DROP TABLE Role CASCADE CONSTRAINTS;